name: "Docker check if image exists"
description: "Check if a Docker image exists"
inputs:
  registry:
    description: "Docker Registry URL"
    required: true
  username:
    description: "Docker Username"
    required: true
  password:
    description: "Docker Password"
    required: true
  image_name:
    description: "Docker Image Name"
    required: true
  tag:
    description: "Docker Tag to be checked"
    required: true
runs:
  using: "composite"
  steps:
    - name: Login to Docker Registry
      shell: bash
      run: echo "${{ inputs.password }}" | docker login -u "${{ inputs.username }}" --password-stdin ${{ inputs.registry }}

    - name: Check if tag exists
      shell: bash
      run: |
        IMAGE_NAME="${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.tag }}"
        echo "Checking if image $IMAGE_NAME exists..."
        if docker pull $IMAGE_NAME; then
          echo "Image $IMAGE_NAME exists."
          exit 1
        else
          echo "Image $IMAGE_NAME does not exist."
        fi