name: "Docker Build & Push"
description: "Build and push a Docker image"
inputs:
  registry:
    description: "Docker Registry URL"
    required: true
  username:
    description: "Docker Username"
    required: true
  password:
    description: "Docker Password"
    required: true
  image_name:
    description: "Docker Image Name"
    required: true
  tag:
    description: "Docker Image Tag"
    required: true
runs:
  using: "composite"
  steps:
    - name: Login to Docker Registry
      shell: bash
      run: echo "${{ inputs.password }}" | docker login -u "${{ inputs.username }}" --password-stdin ${{ inputs.registry }}

    - name: Build Docker Image
      shell: bash
      run: |
        echo "Building Docker image ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.tag }}"
        docker build . -t ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.tag }}

    - name: Push Docker Image
      shell: bash
      run: docker push ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.tag }}
