name: SonarQube Code Quality Check for Python

on:
  workflow_call:
    inputs:
      sonar-project-key:
        description: 'The SonarQube project key for this repository'
        required: true
        type: string

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    name: SonarQube Result Check
    steps:
      - name: Check SonarQube Quality Gate
        run: |
          status=$(curl -s -u ${{ secrets.SONARQUBE_TOKEN }}: "${{ secrets.SONARQUBE_HOST_URL }}/api/qualitygates/project_status?projectKey=${{ inputs.sonar-project-key }}" | jq -r '.projectStatus.status')
          if [ "$status" != "OK" ]; then
            echo "Quality gate failed."
            exit 1
          else
            echo "Quality gate passed."
          fi
