name: SonarQube Code Quality Check for Python

on:
  workflow_call:
    inputs:
      sonarqube-project-key:
        description: 'The SonarQube project key for this repository'
        required: true
        type: string
      sonarqube-version:
        description: 'The version of SonarQube to use'
        required: false
        type: string
        default: '4.6.2.2472'
      python-version:
        description: 'Version of Python to use'
        required: false
        default: '3.8'
        type: string
      install-command:
        description: 'The command to install dependencies'
        required: false
        default: 'pip install -r requirements.txt'
        type: string
      tests-command:
        description: 'The command to run the tests'
        required: false
        default: 'coverage run -m pytest && coverage xml -o coverage.xml'
        type: string
      check-result:
        description: 'Whether to check the SonarQube result'
        required: false
        default: true
        type: boolean
    secrets:
      SONARQUBE_HOST_URL:
        description: 'The SonarQube host URL'
        required: true
      SONARQUBE_TOKEN:
        description: 'The SonarQube authentication token'
        required: true

jobs:
  sonarqube-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Dependencies
        if: ${{ inputs.install-command != '' }}
        run: |
          ${{ inputs.install-command }}
          pip3 install pytest coverage

      - name: Run Tests
        if: ${{ inputs.tests-command != '' }}
        run: |
          ${{ inputs.tests-command }}

      # Sonar Qube
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}

  sonarqube-check:
    needs: sonarqube-scan
    uses: axprueba/workflows/.github/workflows/check-sonarqube.yml@master
    with:
      sonarqube-project-key: ${{ inputs.sonarqube-project-key }}
    secrets:
      SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
      SONARQUBE_HOST_URL: ${{ secrets.SONARQUBE_HOST_URL }}
    if: ${{ inputs.check-result == true }}