name: Run Python Tests

on:
  workflow_call:
    inputs:
      environment:
        description: 'Entorno de ejecución'
        type: string
      python-version:
        description: 'Versión de Python a usar'
        type: string
      
jobs:
  tests:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    name: Run Python Tests
    steps:
      - name: Debug
        run: "echo \"Running for: '${{ inputs.environment }}', ENVIRON_VARIABLE content: '${{ env.ENVIRON_VARIABLE }}'\""

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest