name: Run Python Tests

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Versión de Python a usar'
        type: string

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run Python Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest